# SPDX-FileCopyrightText: 2026 aerynOS Developers
# SPDX-License-Identifier: MPL-2.0

[default]
extend-ignore-re = [
    # Ignore blocks between `spellchecker:off` and `spellchecker:on`
    "spellchecker:off.*?\\n*.*spellchecker:on",
]

[default.extend-words]
# Specifically for the "General FAQ" page.
aer = "aer"

[files]
extend-exclude = ["/package-lock.json"]
