# SPDX-FileCopyrightText: 2026 aerynOS Developers
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meta:
    runs-on: ubuntu-latest
    name: Non-code Checks

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Check for typos
        uses: crate-ci/typos@v1.48.0
